import { z } from 'zod';
import { zodToJsonSchema } from 'zod-to-json-schema';
import { GoogleGenerativeAI } from '@google/generative-ai';

export interface SDKOptions {
  model?: string;
  temperature?: number;
  maxTokens?: number;
}

export class GeminiSDK {
  private static apiKey = process.env.GEMINI_API_KEY || '';
  private static genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');
  
  private static defaultModel = 'gemini-3.5-flash';
  private static fastModel = 'gemini-3.5-flash-lite';
  
  // Gemini 3.5 Flash is the latest stable version with massive free tier limits
  // Priority ordered fallback list to bypass 429 limits
  private static fallbackModels = [
    'gemini-3.5-flash',
    'gemini-flash-lite-latest',
    'gemini-flash-latest',
    'gemini-2.0-flash-001'
  ];

  public static async generateStructuredResponse<T>(
    systemPrompt: string,
    messages: { role: 'user' | 'assistant' | 'system', content: string }[],
    schema: z.ZodType<T>,
    options: { temperature?: number, model?: string } = {}
  ): Promise<{ data: T, usage: any }> {
    
    const formattedMessages = messages.map(m => ({
      role: m.role === 'assistant' ? 'model' : 'user',
      parts: [{ text: m.content }]
    }));

    const schemaString = JSON.stringify(zodToJsonSchema(schema as any), null, 2);
    const enhancedPrompt = `${systemPrompt}\n\nIMPORTANT: You must respond with ONLY a valid JSON object matching this schema. Do not include any other text, markdown blocks, or greetings:\n${schemaString}`;

    // Build a unique list of fallback models. This ensures we don't try the same model twice,
    // and provides alternatives if the free tier quota for 3.5-flash is exhausted.
    const baseModels = ['gemini-3.5-flash', 'gemini-flash-lite-latest', 'gemini-2.0-flash-001', 'gemini-1.5-flash'];
    const modelsToTry = Array.from(new Set(
      options.model ? [options.model, ...baseModels] : baseModels
    ));
    
    let lastError: any = null;

    for (const modelName of modelsToTry) {
      let attempts = 0;
      const maxAttempts = 1; // Only 1 attempt per model to guarantee sub-5s response times
      
      while (attempts < maxAttempts) {
        attempts++;
        let responseText = "";
        try {
          const model = this.genAI.getGenerativeModel({ model: modelName, systemInstruction: enhancedPrompt });
          
          const result = await model.generateContent({
            contents: formattedMessages,
            generationConfig: {
              temperature: options.temperature ?? 0.1,
              // Removed responseMimeType as it causes truncated JSON bugs in some Gemini versions
            }
          });
          
          responseText = result.response.text();
          
          // Clean up markdown code blocks if the model outputs them anyway
          let cleanText = responseText.replace(/^```json/mi, '').replace(/```$/m, '').trim();
          
          // Hack to fix double trailing brackets sometimes generated by Gemini
          if (cleanText.endsWith('}\n}')) {
             cleanText = cleanText.slice(0, -2);
          }
          if (cleanText.endsWith('} }')) {
             cleanText = cleanText.slice(0, -2);
          }
          
          // Hack to fix missing closing bracket
          if (!cleanText.endsWith('}')) {
             cleanText += '}';
          }

          const parsedData = JSON.parse(cleanText);
          const validatedData = schema.parse(parsedData);
          
          return { data: validatedData, usage: result.response.usageMetadata };

        } catch (error: any) {
          lastError = error;
          
          if (error.status === 429 || error.message?.includes('429') || error.message?.includes('Quota') || error.message?.includes('fetch')) {
            console.warn(`[GeminiSDK] ${modelName} failed (Rate Limit/API). Falling back...`);
            break;
          }

          console.warn(`[GeminiSDK] Parsing/Validation failed on ${modelName}: ${error.message}`);
          console.warn("Raw Output:", responseText);
          break; // Don't retry, just fail to the next model to save time
        }
      }
    }

    throw new Error(`All fallback models exhausted. Last error: ${lastError?.message}`);
  }

  /**
   * streamChat
   */
  static async streamChat(
    systemPrompt: string, 
    messages: { role: string; content: string }[], 
    options: SDKOptions = {}
  ): Promise<ReadableStream> {
    throw new Error("Not implemented yet for generic streaming in this scaffold");
  }

  /**
   * classifyIntent
   */
  static async classifyIntent(
    userMessage: string,
    intents: string[]
  ): Promise<string> {
    const prompt = `Classify the following message into one of these intents: [${intents.join(', ')}]. Respond with ONLY the exact intent name string. Nothing else.`;
    
    const model = this.genAI.getGenerativeModel({ 
      model: this.fastModel,
      systemInstruction: prompt
    });

    const result = await model.generateContent(userMessage);
    return result.response.text().trim();
  }

  /**
   * summarize
   */
  static async summarize(text: string, options: SDKOptions = {}): Promise<string> {
    const model = this.genAI.getGenerativeModel({ 
      model: options.model || this.defaultModel,
      systemInstruction: 'You are a master summarizer. Summarize the following text concisely.'
    });

    const result = await model.generateContent(text);
    return result.response.text();
  }
  
  /**
   * extractStructuredData
   */
  static async extractStructuredData<T>(text: string, schema: z.ZodType<T>): Promise<T> {
     const res = await this.generateStructuredResponse(
       "Extract the relevant financial entities from this text into JSON.",
       [{ role: "user", content: text }],
       schema,
       { temperature: 0 }
     );
     return res.data;
  }
}
